{% set name = "Unidecode" %}
{% set version = "1.3.0" %}
{% set sha256 = "9f8235681cc520912fe02e7dd73d455c2f0471f39d36485bc278b97b3e2f2390" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unidecode = unidecode.util:main

requirements:
  host:
    - pip
    - python 2.7|>=3.5
  run:
    - python 2.7|>=3.5

test:
  imports:
    - unidecode
  commands:
    - unidecode --help

about:
  home: https://pypi.python.org/pypi/Unidecode
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: ASCII transliterations of Unicode text
  dev_url: https://www.tablix.org/~avian/git/unidecode.git

extra:
  recipe-maintainers:
    - synapticarbors
