{% set name = "Unidecode" %}
{% set version = "1.3.1" %}
{% set sha256 = "6efac090bf8f29970afc90caf4daae87b172709b786cb1b4da2d0c0624431ecc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unidecode = unidecode.util:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - unidecode
  commands:
    - unidecode --help

about:
  home: https://pypi.python.org/pypi/Unidecode
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: ASCII transliterations of Unicode text
  dev_url: https://github.com/avian2/unidecode

extra:
  recipe-maintainers:
    - synapticarbors
