{% set name = "Unidecode" %}
{% set version = "1.3.8" %}
{% set sha256 = "cfdb349d46ed3873ece4586b96aa75258726e2fa8ec21d6f00a591d98806c2f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unidecode = unidecode.util:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - unidecode
  commands:
    - unidecode --help

about:
  home: https://pypi.python.org/pypi/Unidecode
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: ASCII transliterations of Unicode text
  dev_url: https://github.com/avian2/unidecode

extra:
  recipe-maintainers:
    - synapticarbors
